### PR TITLE
Expose port 9200 outside vagrant

### PR DESCRIPTION
**Pull request by SebastinSanty**

### CODE REVIEW

**Comment by SebastinSanty** [comment]
#125

**Comment by prasadtalasila** [comment]
A compatile matching changes need to me made on [elasticsearc.proprrties](https://github.com/prasadtalasila/BITS-Darshini/blob/dev/src/main/resources/META-INF/elasticsearch.properties#L4).

**Comment by prasadtalasila** [comment]
There is another ES config file in [conf/](https://github.com/prasadtalasila/BITS-Darshini/blob/dev/conf/elasticsearch.properties#L4) directory. Even this needs to be updated.

**Comment by prasadtalasila** [comment]
problem fixed in  Commit 65c3344

**Pull request closed without merging**
