### PR TITLE
rectifies some code quality issues for tests suggested by codeclimate

### PR DESCRIPTION
**Pull request by adityaketkar**

### CODE REVIEW

**Comment by adityaketkar** [comment]
@prasadtalasila the coverage as shown by eclipse is still unchaged, but codecov is indicating otherwise.
I am pretty sure that the tests still cover classes. For example, running tests locally (using eclipse coverage), IPv4Analyzer.java is covered to 93.8% for the same build, but codecov says its 0%.
Please see the screenshot below :  
image

**Comment by prasadtalasila** [comment]
@adityaketkar I cloned your dev branch and ran the unit tests in my Eclipse. The code coverage results reported by Eclipse on my computer are consistent with the results shown by codecov. Is your Eclipse code consistent with (same) as the your latest dev branch code?

You did change the ExperimentTest.java code. Please check the test files again.

**Comment by adityaketkar** [comment]
@prasadtalasila Can you please confirm the coverage of IPv4Analyzer.java in your [dev](https://github.com/prasadtalasila/BITS-Darshini/tree/dev) branch.

**Comment by prasadtalasila** [comment]
coverage
@adityaketkar The above is image for the latest commit on the dev branch.

**Pull request merged**
